import { safeStorage, shell } from "electron";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createHash, randomBytes } from "node:crypto";
import {
  clearLinkForEvent,
  clearLinkForMeeting,
  deleteCalendarAccount as dbDeleteAccount,
  getCalendarAccount,
  getCalendarEventForMeeting,
  getMeeting,
  insertCalendarAccount,
  isMeetingTitleAutoGenerated,
  linkCalendarEventToMeeting,
  listCalendarAccounts as dbListAccounts,
  listCalendarEvents as dbListEvents,
  listCalendarEventsOverlapping,
  listLinkedMeetingIds,
  listSpeakers,
  listVoiceLibrary,
  setTitle,
  updateCalendarAccountTokens,
  upsertCalendarEvent,
  type CalendarAccountRow,
  type CalendarEventRow,
} from "./db.js";
import { getGoogleCredentials } from "./calendar-settings.js";
import {
  findMatchingEvent,
  isEventActiveAt,
  rankCandidates,
  type MatchCandidate,
} from "./calendar-match.js";

const OAUTH_SCOPES = [
  "https://www.googleapis.com/auth/calendar.readonly",
  "https://www.googleapis.com/auth/userinfo.email",
  "openid",
];

function encryptToken(value: string | null): string | null {
  if (!value) return null;
  if (!safeStorage.isEncryptionAvailable()) {
    return Buffer.from(`plain:${value}`, "utf8").toString("base64");
  }
  return safeStorage.encryptString(value).toString("base64");
}

function decryptToken(value: string | null): string | null {
  if (!value) return null;
  const buf = Buffer.from(value, "base64");
  if (buf.toString("utf8").startsWith("plain:")) {
    return buf.toString("utf8").slice("plain:".length);
  }
  try {
    return safeStorage.decryptString(buf);
  } catch {
    return null;
  }
}

export interface CalendarAccountPublic {
  id: string;
  email: string;
  provider: "google";
  connected_at_ms: number;
}

export function listAccounts(): CalendarAccountPublic[] {
  return dbListAccounts().map((a) => ({
    id: a.id,
    email: a.email,
    provider: a.provider,
    connected_at_ms: a.created_at_ms,
  }));
}

export function disconnectAccount(id: string): void {
  dbDeleteAccount(id);
}

interface GoogleTokenResponse {
  access_token: string;
  refresh_token?: string;
  expires_in: number;
  token_type: string;
  scope: string;
  id_token?: string;
}

interface GoogleUserInfo {
  email: string;
  sub: string;
}

/** Generate a PKCE code_verifier + S256 challenge. */
function makePkce(): { verifier: string; challenge: string } {
  const verifier = randomBytes(32).toString("base64url");
  const challenge = createHash("sha256").update(verifier).digest("base64url");
  return { verifier, challenge };
}

/**
 * Run Google OAuth using the loopback (installed-app) flow:
 *  - spin a one-shot HTTP server on 127.0.0.1:<random>
 *  - open Google's auth URL in the user's real browser
 *  - catch the redirected ?code=... on /callback
 *  - exchange code for tokens with PKCE verifier
 */
export async function connectGoogleAccount(): Promise<CalendarAccountPublic> {
  const creds = await getGoogleCredentials();
  if (!creds) {
    throw new Error(
      "No Google credentials configured. Add Client ID + Client secret in the Calendar panel.",
    );
  }

  const { code, redirectUri, verifier } = await runLoopbackOAuth(creds.clientId);
  const tokens = await exchangeCodeForTokens({
    clientId: creds.clientId,
    clientSecret: creds.clientSecret,
    code,
    redirectUri,
    verifier,
  });

  const userInfo = await fetchUserInfo(tokens.access_token);
  const expiresAtMs = Date.now() + (tokens.expires_in - 30) * 1000;

  const account = insertCalendarAccount({
    provider: "google",
    email: userInfo.email,
    accessTokenEnc: encryptToken(tokens.access_token),
    refreshTokenEnc: encryptToken(tokens.refresh_token ?? null),
    tokenExpiresAtMs: expiresAtMs,
  });

  return {
    id: account.id,
    email: account.email,
    provider: account.provider,
    connected_at_ms: account.created_at_ms,
  };
}

const OAUTH_TIMEOUT_MS = 5 * 60 * 1000;

function successHtml(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>Scribe — connected</title>
<style>
  body { font: 15px/1.4 -apple-system, system-ui, sans-serif; background:#0b0b0d; color:#fafafa;
         display:flex; align-items:center; justify-content:center; height:100vh; margin:0; }
  .card { max-width:420px; padding:32px; border:1px solid #2a2a2e; border-radius:14px; text-align:center; }
  h1 { font-size:18px; margin:0 0 8px; }
  p  { color:#a1a1aa; margin:0; }
</style></head><body>
<div class="card">
  <h1>✓ Connected to Google Calendar</h1>
  <p>You can close this tab and return to Scribe.</p>
</div></body></html>`;
}

function errorHtml(msg: string): string {
  const safe = msg.replace(/[<>&]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" })[c]!);
  return `<!doctype html><html><body style="font-family:sans-serif;padding:32px">
<h1>OAuth error</h1><p>${safe}</p></body></html>`;
}

function runLoopbackOAuth(clientId: string): Promise<{
  code: string;
  redirectUri: string;
  verifier: string;
}> {
  return new Promise((resolve, reject) => {
    const state = randomBytes(16).toString("base64url");
    const pkce = makePkce();
    // Captured at listen() time, BEFORE the server is closed — so the request
    // handler can reference it even after cleanup() runs.
    let redirectUri = "";

    const server = createServer((req: IncomingMessage, res: ServerResponse) => {
      try {
        const url = new URL(req.url ?? "/", `http://127.0.0.1`);
        if (url.pathname !== "/callback") {
          res.statusCode = 404;
          res.end("Not found");
          return;
        }
        const incomingState = url.searchParams.get("state");
        const code = url.searchParams.get("code");
        const err = url.searchParams.get("error");

        if (err) {
          res.setHeader("Content-Type", "text/html");
          res.end(errorHtml(`Google returned: ${err}`));
          cleanup();
          reject(new Error(`OAuth error: ${err}`));
          return;
        }
        if (!code || incomingState !== state) {
          res.setHeader("Content-Type", "text/html");
          res.end(errorHtml("Missing code or state mismatch."));
          cleanup();
          reject(new Error("OAuth callback missing code / state mismatch"));
          return;
        }
        res.setHeader("Content-Type", "text/html");
        res.end(successHtml());
        cleanup();
        resolve({
          code,
          redirectUri,
          verifier: pkce.verifier,
        });
      } catch (e) {
        cleanup();
        reject(e instanceof Error ? e : new Error(String(e)));
      }
    });

    const timer = setTimeout(() => {
      cleanup();
      reject(new Error("OAuth timed out — no response from Google"));
    }, OAUTH_TIMEOUT_MS);

    function cleanup() {
      clearTimeout(timer);
      try {
        server.close();
      } catch {
        /* ignore */
      }
    }

    // Port 0 → OS picks a free port. Then build the auth URL with that
    // port baked into redirect_uri (Google must see an exact match).
    server.listen(0, "127.0.0.1", () => {
      const addr = server.address();
      const port = typeof addr === "object" && addr ? addr.port : 0;
      redirectUri = `http://127.0.0.1:${port}/callback`;

      const authUrl = new URL("https://accounts.google.com/o/oauth2/v2/auth");
      authUrl.searchParams.set("client_id", clientId);
      authUrl.searchParams.set("redirect_uri", redirectUri);
      authUrl.searchParams.set("response_type", "code");
      authUrl.searchParams.set("scope", OAUTH_SCOPES.join(" "));
      authUrl.searchParams.set("access_type", "offline");
      authUrl.searchParams.set("prompt", "consent");
      authUrl.searchParams.set("state", state);
      authUrl.searchParams.set("code_challenge", pkce.challenge);
      authUrl.searchParams.set("code_challenge_method", "S256");

      void shell.openExternal(authUrl.toString());
    });

    server.on("error", (e) => {
      cleanup();
      reject(e);
    });
  });
}

async function exchangeCodeForTokens(opts: {
  clientId: string;
  clientSecret: string;
  code: string;
  redirectUri: string;
  verifier: string;
}): Promise<GoogleTokenResponse> {
  const body = new URLSearchParams({
    code: opts.code,
    client_id: opts.clientId,
    client_secret: opts.clientSecret,
    redirect_uri: opts.redirectUri,
    grant_type: "authorization_code",
    code_verifier: opts.verifier,
  });
  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Token exchange failed: ${res.status} ${text}`);
  }
  return (await res.json()) as GoogleTokenResponse;
}

async function refreshAccessToken(
  account: CalendarAccountRow,
): Promise<{ accessToken: string; expiresAtMs: number }> {
  const creds = await getGoogleCredentials();
  if (!creds) throw new Error("Missing Google credentials");
  const refresh = decryptToken(account.refresh_token_enc);
  if (!refresh) throw new Error("Account has no refresh token — reconnect required");

  const body = new URLSearchParams({
    client_id: creds.clientId,
    client_secret: creds.clientSecret,
    refresh_token: refresh,
    grant_type: "refresh_token",
  });
  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Token refresh failed: ${res.status} ${text}`);
  }
  const json = (await res.json()) as GoogleTokenResponse;
  const expiresAtMs = Date.now() + (json.expires_in - 30) * 1000;
  updateCalendarAccountTokens({
    id: account.id,
    accessTokenEnc: encryptToken(json.access_token),
    refreshTokenEnc: account.refresh_token_enc,
    tokenExpiresAtMs: expiresAtMs,
  });
  return { accessToken: json.access_token, expiresAtMs };
}

async function getValidAccessToken(account: CalendarAccountRow): Promise<string> {
  const now = Date.now();
  if (
    account.access_token_enc &&
    account.token_expires_at_ms &&
    account.token_expires_at_ms > now + 5000
  ) {
    const t = decryptToken(account.access_token_enc);
    if (t) return t;
  }
  const refreshed = await refreshAccessToken(account);
  return refreshed.accessToken;
}

async function fetchUserInfo(accessToken: string): Promise<GoogleUserInfo> {
  const res = await fetch("https://openidconnect.googleapis.com/v1/userinfo", {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error(`userinfo failed: ${res.status}`);
  return (await res.json()) as GoogleUserInfo;
}

interface GoogleCalendarEvent {
  id: string;
  summary?: string;
  description?: string;
  location?: string;
  htmlLink?: string;
  hangoutLink?: string;
  start?: { dateTime?: string; date?: string };
  end?: { dateTime?: string; date?: string };
  attendees?: GoogleCalendarAttendee[];
  status?: string;
}

interface GoogleCalendarAttendee {
  email: string;
  displayName?: string;
  responseStatus?: string;
  self?: boolean;
  resource?: boolean;
  organizer?: boolean;
  optional?: boolean;
}

function dateToMs(d?: { dateTime?: string; date?: string }): number | null {
  if (!d) return null;
  if (d.dateTime) return Date.parse(d.dateTime);
  if (d.date) return Date.parse(d.date + "T00:00:00");
  return null;
}

export async function syncAccountEvents(opts: {
  accountId: string;
  fromMs: number;
  toMs: number;
}): Promise<{ count: number }> {
  const account = getCalendarAccount(opts.accountId);
  if (!account) throw new Error("Account not found");
  const token = await getValidAccessToken(account);

  const params = new URLSearchParams({
    singleEvents: "true",
    orderBy: "startTime",
    timeMin: new Date(opts.fromMs).toISOString(),
    timeMax: new Date(opts.toMs).toISOString(),
    maxResults: "250",
  });

  const res = await fetch(
    `https://www.googleapis.com/calendar/v3/calendars/primary/events?${params}`,
    { headers: { Authorization: `Bearer ${token}` } },
  );
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Calendar list failed: ${res.status} ${text}`);
  }
  const json = (await res.json()) as { items?: GoogleCalendarEvent[] };
  let count = 0;
  for (const ev of json.items ?? []) {
    if (ev.status === "cancelled") continue;
    const start = dateToMs(ev.start);
    const end = dateToMs(ev.end);
    if (start == null || end == null) continue;
    upsertCalendarEvent({
      accountId: account.id,
      sourceEventId: ev.id,
      title: ev.summary ?? "(no title)",
      description: ev.description ?? null,
      location: ev.location ?? null,
      startAtMs: start,
      endAtMs: end,
      hangoutLink: ev.hangoutLink ?? ev.htmlLink ?? null,
      attendeesJson: ev.attendees ? JSON.stringify(ev.attendees) : null,
    });
    count++;
  }
  return { count };
}

export function listEvents(fromMs: number, toMs: number) {
  return dbListEvents(fromMs, toMs);
}

// --- Linking -----------------------------------------------------------------

const MATCH_WINDOW_MS = 4 * 60 * 60 * 1000;

export interface LinkResult {
  linked: boolean;
  event: CalendarEventRow | null;
  confidence: number;
  reason: string | null;
  titleRenamed: boolean;
}

/**
 * Format the auto-generated meeting title as "<event title> · YYYY-MM-DD".
 * ISO date keeps recurring meetings sortable and locale-independent.
 */
function buildAutoTitle(eventTitle: string, startedAtMs: number): string {
  const d = new Date(startedAtMs);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${eventTitle} · ${y}-${m}-${day}`;
}

/**
 * Find the best calendar match for a recording and persist the link if the
 * matcher is confident. Optionally pre-fills the recording's title from the
 * event when it's still the auto-generated default.
 */
export function autoLinkMeeting(opts: {
  meetingId: string;
  renameIfAuto: boolean;
}): LinkResult {
  const meeting = getMeeting(opts.meetingId);
  if (!meeting) return emptyResult();

  // Look at events overlapping a wide window centered on the recording.
  const start = meeting.started_at_ms - MATCH_WINDOW_MS;
  const end =
    (meeting.ended_at_ms ?? meeting.started_at_ms + MATCH_WINDOW_MS) +
    MATCH_WINDOW_MS;
  const events = listCalendarEventsOverlapping(start, end);
  const match = findMatchingEvent(
    {
      id: meeting.id,
      title: meeting.title,
      started_at_ms: meeting.started_at_ms,
      ended_at_ms: meeting.ended_at_ms,
    },
    events,
  );
  if (!match) return emptyResult();

  // If the event is already linked to a different meeting, don't steal it.
  if (match.event.meeting_id && match.event.meeting_id !== meeting.id) {
    return emptyResult();
  }

  // Make sure no other event points at this meeting (one-to-one).
  clearLinkForMeeting(meeting.id);
  linkCalendarEventToMeeting(match.event.id, meeting.id);

  let renamed = false;
  if (opts.renameIfAuto && isMeetingTitleAutoGenerated(opts.meetingId)) {
    setTitle(opts.meetingId, buildAutoTitle(match.event.title, meeting.started_at_ms));
    renamed = true;
  }

  return {
    linked: true,
    event: { ...match.event, meeting_id: meeting.id },
    confidence: match.confidence,
    reason: match.reason,
    titleRenamed: renamed,
  };
}

function emptyResult(): LinkResult {
  return {
    linked: false,
    event: null,
    confidence: 0,
    reason: null,
    titleRenamed: false,
  };
}

/**
 * List nearby calendar events ranked by match score for a recording —
 * powers the manual "Link to event…" picker.
 */
export function listLinkCandidates(meetingId: string): MatchCandidate[] {
  const meeting = getMeeting(meetingId);
  if (!meeting) return [];
  const start = meeting.started_at_ms - 24 * 60 * 60 * 1000;
  const end =
    (meeting.ended_at_ms ?? meeting.started_at_ms) + 24 * 60 * 60 * 1000;
  const events = listCalendarEventsOverlapping(start, end);
  return rankCandidates(
    {
      id: meeting.id,
      title: meeting.title,
      started_at_ms: meeting.started_at_ms,
      ended_at_ms: meeting.ended_at_ms,
    },
    events,
  );
}

export function linkEventToMeeting(eventId: string, meetingId: string): void {
  clearLinkForMeeting(meetingId);
  clearLinkForEvent(eventId);
  linkCalendarEventToMeeting(eventId, meetingId);
}

export function unlinkMeeting(meetingId: string): void {
  clearLinkForMeeting(meetingId);
}

export function getLinkedEventForMeeting(
  meetingId: string,
): CalendarEventRow | null {
  return getCalendarEventForMeeting(meetingId);
}

export function listLinkedMeetingIdsPublic(): string[] {
  return listLinkedMeetingIds();
}

// --- Attendees ---------------------------------------------------------------

export interface MeetingAttendee {
  email: string;
  /** displayName when present, else email local-part — never empty. */
  name: string;
  responseStatus: string | null;
  /** Calendar owner's own attendee row — usually the user. */
  self: boolean;
  /** Speaker_id (in the current meeting) this attendee is already tagged as,
   *  matched by exact display_name equality. UI uses this to disable chips. */
  assignedTo: string | null;
  /** Existing voice library entry matching this name. UI uses this to route
   *  to assignToLibrary instead of createFromSpeaker on click. */
  libraryId: string | null;
}

function emailLocalPart(email: string): string {
  const at = email.indexOf("@");
  return at > 0 ? email.slice(0, at) : email;
}

function parseAttendees(json: string | null): GoogleCalendarAttendee[] {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return Array.isArray(parsed) ? (parsed as GoogleCalendarAttendee[]) : [];
  } catch {
    return [];
  }
}

/** Attendees worth showing as speaker candidates: drop room/resource calendars
 *  and people who declined. Keeps `self` (user is in the recording too). */
function speakingAttendees(
  attendees: GoogleCalendarAttendee[],
): GoogleCalendarAttendee[] {
  return attendees.filter(
    (a) => !a.resource && a.responseStatus !== "declined",
  );
}

/**
 * Enriched attendee list for the voice-tagging panel: tells the UI which
 * attendees are already tagged in this meeting and which are recognized
 * across the voice library.
 */
export function getMeetingAttendees(meetingId: string): MeetingAttendee[] {
  const event = getCalendarEventForMeeting(meetingId);
  if (!event) return [];
  const raw = speakingAttendees(parseAttendees(event.attendees_json));
  if (raw.length === 0) return [];

  const speakers = listSpeakers(meetingId);
  const library = listVoiceLibrary();
  // Index by lowercased name so "alice" === "Alice".
  const speakerByName = new Map<string, string>();
  for (const s of speakers) {
    if (s.display_name) {
      speakerByName.set(s.display_name.toLowerCase(), s.speaker_id);
    }
  }
  // Two indexes: email is the stable identity (preferred), name is the
  // fragile fallback for voice-only people who have no email yet.
  const libraryByName = new Map<string, string>();
  const libraryByEmail = new Map<string, string>();
  for (const l of library) {
    libraryByName.set(l.display_name.toLowerCase(), l.id);
    if (l.email) libraryByEmail.set(l.email.toLowerCase(), l.id);
  }

  const out: MeetingAttendee[] = raw.map((a) => {
    const name = (a.displayName ?? "").trim() || emailLocalPart(a.email);
    const key = name.toLowerCase();
    const libraryId =
      (a.email ? libraryByEmail.get(a.email.toLowerCase()) : undefined) ??
      libraryByName.get(key) ??
      null;
    return {
      email: a.email,
      name,
      responseStatus: a.responseStatus ?? null,
      self: !!a.self,
      assignedTo: speakerByName.get(key) ?? null,
      libraryId,
    };
  });

  // Sort: not-yet-assigned first, then recognized (already in library), then
  // self (you), then everyone else alphabetically. Putting `self` after
  // recognized assumes the user is usually less interesting to tag than the
  // counterparts they're meeting with.
  out.sort((a, b) => {
    if (!!a.assignedTo !== !!b.assignedTo) return a.assignedTo ? 1 : -1;
    if (!!a.libraryId !== !!b.libraryId) return a.libraryId ? -1 : 1;
    if (a.self !== b.self) return a.self ? 1 : -1;
    return a.name.localeCompare(b.name);
  });
  return out;
}

/**
 * Upper-bound hint for diarization based on the linked event's invitee list.
 * Returns 0 (== "no hint") when there's no event or no usable attendees.
 *
 * We add +1 to the count to leave room for an uninvited speaker (drop-ins are
 * common) and cap at 12 to keep pyannote's clustering well-behaved.
 */
export function speakerHintForMeeting(meetingId: string): {
  minSpeakers: number;
  maxSpeakers: number;
} {
  const event = getCalendarEventForMeeting(meetingId);
  if (!event) return { minSpeakers: 0, maxSpeakers: 0 };
  const count = speakingAttendees(parseAttendees(event.attendees_json)).length;
  // For one-attendee events we can't tell solo recordings from short 1-on-1s
  // — leave pyannote to estimate freely rather than risk pinning two
  // clusters on a single speaker.
  if (count <= 1) return { minSpeakers: 0, maxSpeakers: 0 };
  // Set both bounds: leaving min at 0 lets pyannote's clustering threshold
  // merge everything to a single cluster (the failure mode the user just
  // hit on a 9-person meeting). Half-count-rounded-down as a floor strikes
  // a balance — survives a few no-shows but blocks 9 → 1 collapses.
  return {
    minSpeakers: Math.max(2, Math.floor(count / 2)),
    maxSpeakers: Math.min(count + 1, 12),
  };
}

/**
 * Returns the calendar event that "encloses" `now`, if any — used by the
 * Smart Start Scribe button to pre-link before the recording starts.
 */
export function findActiveEventNow(now = Date.now()): CalendarEventRow | null {
  const window = listCalendarEventsOverlapping(
    now - 30 * 60 * 1000,
    now + 30 * 60 * 1000,
  );
  const active = window.filter(
    (ev) => isEventActiveAt(ev, now) && !ev.meeting_id,
  );
  if (active.length === 0) return null;
  // Prefer the one that started most recently (handles back-to-back).
  active.sort((a, b) => b.start_at_ms - a.start_at_ms);
  return active[0];
}
